name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Postman Collection
        id: newman
        shell: bash
        run: |
          set +e

          newman run collections/RestfulBooker.postman_collection.json \
            -e environments/Dev.postman_environment.json \
            -r cli,html \
            --reporter-html-export reports/newman-report.html

          EXIT_CODE=$?

          echo "exit_code=$EXIT_CODE" >> "$GITHUB_OUTPUT"

          exit 0

      - name: Upload Newman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: reports/newman-report.html

      - name: Fail workflow if Newman tests failed
        if: steps.newman.outputs.exit_code != '0'
        run: |
          echo "Newman detected failed tests."
          exit 1